{% set name = "PyWinCtl" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Kalmat/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 959646f9a3f9a47029ce21e9c878abf64406f0c24ba5969143f1226c24c937c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]
    - pywin32 >=302  # [win]
    - python-xlib >=0.21  # [linux]
    - pyobjc-core >=8.1  # [osx]
    - typing_extensions >=4.4.0
    - pywinbox >=0.6
    - pymonctl >=0.6

test:
  commands:
    - "DISPLAY=localhost:1.0 XDG_SESSION_TYPE=x11 xvfb-run -a python -c 'import pywinctl'"  # [linux]
  imports:
    - pywinctl  # [not linux] pywinbox fails on import as no display is available

about:
  home: https://github.com/Kalmat/PyWinCtl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Cross-Platform toolkit to get info on and control windows on screen'
  dev_url: https://github.com/Kalmat/PyWinCtl

extra:
  recipe-maintainers:
    - '0xbe7a'
